### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by gadolf66** [Lochnair/tsping#1]
I'm participating in cake-autorate tests and I'm preparing my environment to be able to execute autorate's next version, when it will start to use tsping.
I'm currently running cake/cake-autorate on a Debian headless router, no issues.
Before installing tsping on the router, I wanted to test it on my Ubuntu 22.04 laptop.
I think it successfully installed and tsping executable was created:

```
gustavo@G15:~/tsping$ sudo meson build .
The Meson build system
Version: 0.61.2
Source dir: /home/gustavo/tsping
Build dir: /home/gustavo/tsping/build
Build type: native build
Project name: tsping
Project version: 0.1
C compiler for the host machine: ccache cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Library argp found: NO
Run-time dependency threads found: YES
Build targets in project: 1

```
```
gustavo@G15:~/tsping/build$ ls -la
total 88
drwxrwxr-x 6 gustavo gustavo  4096 dez 19 08:31 .
drwxrwxr-x 4 gustavo gustavo  4096 dez 19 08:29 ..
-rw-r--r-- 1 root    root     2553 dez 19 08:29 build.ninja
-rw-r--r-- 1 root    root      346 dez 19 08:29 compile_commands.json
-rw-r--r-- 1 root    root       92 dez 19 08:29 .gitignore
-rw-r--r-- 1 root    root      108 dez 19 08:29 .hgignore
drwxr-xr-x 2 root    root     4096 dez 19 08:29 meson-info
drwxr-xr-x 2 root    root     4096 dez 19 08:29 meson-logs
drwxr-xr-x 2 root    root     4096 dez 19 08:29 meson-private
-rw-r--r-- 1 root    root     7076 dez 19 08:31 .ninja_deps
-rw-r--r-- 1 root    root      125 dez 19 08:31 .ninja_log
-rwxr-xr-x 1 root    root    34344 dez 19 08:31 tsping
drwxr-xr-x 2 root    root     4096 dez 19 08:31 tsping.p

Found ninja-1.10.1 at /usr/bin/ninja
```

However when I run tsping 1.1.1.1, it seems to stall, no output at all.
Can this be a firewall issue?

**Comment by Lochnair** [comment]
It is likely a firewall issue yes, but on 1.1.1.1's side. I get no responses to ICMP timestamp requests from them either.
You can verify that ICMP echo requests (standard ping) works as expected with the `-e` option.

```
sudo ./tsping -e 1.1.1.1
1.1.1.1         : [0], 32 ms
1.1.1.1         : [1], 36 ms
```

Quad9's DNS servers however respond properly:

```
sudo ./tsping 9.9.9.9
9.9.9.9         : [0] Down: 19, Up: 16, RTT: 35, Originate: 43781669, Received: 43781685, Transmit: 43781685, Finished: 43781704
9.9.9.9         : [1] Down: 21, Up: 17, RTT: 38, Originate: 43781769, Received: 43781786, Transmit: 43781786, Finished: 43781807
9.9.9.9         : [2] Down: 23, Up: 16, RTT: 39, Originate: 43781869, Received: 43781885, Transmit: 43781885, Finished: 43781908
```

**Comment by gadolf66** [comment]
Indeed, `tsping -e` works as expected.
But `tsping 9.9.9.9` still hangs.
Which port(s) should I open in the firewall?

**Comment by gadolf66** [comment]
In parallel, I'm installing tsping on the Debian server, since it's there where it will be used.
However, I got this build error:
```
gustavo@srv:~/tsping/build/meson-logs$ cat meson-log.txt 
Build started at 2022-12-19T09:51:31.611475
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.49.2
Source dir: /opt/tsping
Build dir: /home/gustavo/tsping/build
Build type: native build
Project name: tsping
Project version: 0.1
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /home/gustavo/tsping/build/meson-private/sanitycheckc.c -o /home/gustavo/tsping/build/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/gustavo/tsping/build/meson-private/sanitycheckc.exe
Native C compiler: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64

meson.build:6:0: ERROR:  Tried to access unknown option "argp_standalone".

```

**Comment by Lochnair** [comment]
> But tsping 9.9.9.9 still hangs.
> Which port(s) should I open in the firewall?

Ah, local or ISP firewall filtering then.
ICMP doesn't have a concept of ports, so if it's on your end, it's likely that you need to allow ICMP type 13/14.
I don't know that firewall you're using, so I'll give an example rule in nftables:
```
icmp type {timestamp-request, timestamp-reply} accept
```

> In parallel, I'm installing tsping on the Debian server, since it's there where it will be used.
> However, I got this build error:

That's odd. The options are defined in meson_options.txt, so you should have that in your ~/tsping folder.
The option was just a quick-fix for getting this to work on OpenWrt as well (argp isn't included in musl libc, thus argp-standalone is required).
But I've gone ahead and pushed https://github.com/Lochnair/tsping/commit/6a7cb1f0d616db848b1ba02886a0d7505cbbf55e which should handle this in a better way, so please pull the latest changes and give that a try.

**Comment by gadolf66** [comment]
Great! Now it works.
But... it only works if I build it into the source directory, like this:
```
gustavo@srv:~/tsping$ sudo meson build .
The Meson build system
Version: 0.49.2
Source dir: /home/gustavo/tsping
Build dir: /home/gustavo/tsping/build
Build type: native build
Project name: tsping
Project version: 0.1
Native C compiler: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES 
Checking if "argp test" links: YES
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja
```
If I try to build it into another _builddir_ I get this:
`
gustavo@srv:~/tsping$ sudo meson build /opt/tsping
ERROR: Neither directory contains a build file meson.build.
`
I have already created /opt/tsping and copied _meson.build_ into it, but then it asks for _main.c_...

Not a big issue, since I can move the binary to that location, but just to let you know

**Comment by Lochnair** [comment]
That was a mistake in the readme on my part. Running just `meson` will have the same effect as `meson setup`, which takes these arguments:

>positional arguments:
> * builddir
> * sourcedir

So what actually happens is that in effect you're running `meson setup build /opt/tsping`, which would explain your error.
If you instead do `meson setup /opt/tsping` you should be fine.

**Comment by gadolf66** [comment]
Ah, good, _setup_ worked, but I can't find the binary.
To avoid further confusion, here's what have:
1 - Clone directory in ~/tsping
2 - Build directory in /opt/tsping (I'm assuming that by _build_ it means the directory where the binary will be placed)

The steps are
1) clone
2) cd ~/tsping
3) sudo meson setup /opt/tsping (it creates /opt/tsping)
4)sudo meson compile

In the end, there's no binary, but also, no error ...
[meson-log.txt](https://github.com/Lochnair/tsping/files/10259987/meson-log.txt)

**Comment by Lochnair** [comment]
That was a mistake in the readme on my part. Running just `meson` will have the same effect as `meson setup`, which takes these arguments:

>positional arguments:
> * builddir
> * sourcedir

So what actually happens is that in effect you're running `meson setup build /opt/tsping`, which would explain your error.
If you instead do `meson setup /opt/tsping` you should be fine.

**Comment by gadolf66** [comment]
So to simplify things I followed these instructions literally:

```
git clone https://github.com/Lochnair/tsping.git
cd tsping
meson setup builddir
cd builddir
meson compile
```
that is, I named the target directory as _builddir_.
_meson setup builddir_ runs ok and creates a _builddir_ directory inside ~/tsping
Then I cd builddir and

```
gustavo@srv:~$ git clone https://github.com/Lochnair/tsping.git
Cloning into 'tsping'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 74 (delta 40), reused 32 (delta 4), pack-reused 0
Unpacking objects: 100% (74/74), done.
gustavo@srv:~$ cd tsping/
gustavo@srv:~/tsping$ git pull
Already up to date.
gustavo@srv:~/tsping$ meson setup builddir
The Meson build system
Version: 0.49.2
Source dir: /home/gustavo/tsping
Build dir: /home/gustavo/tsping/builddir
Build type: native build
Project name: tsping
Project version: 0.1
Native C compiler: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES 
Checking if "argp test" links: YES
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja
gustavo@srv:~/tsping$ ls
args.h  builddir  LICENSE.md  main.c  meson.build  README.md  strtonum.h  tsping.h
gustavo@srv:~/tsping$ cd builddir/
gustavo@srv:~/tsping/builddir$ meson compile

ERROR: Neither directory contains a build file meson.build.

```

I can't reproduce the random steps I took on my Ubuntu laptop where I could build tsping.

**Comment by gadolf66** [comment]
Found it!
Worng meson version in Debian (0.46)
I installed latest stable meson (0.64) and it worked.
Sorry for having taken your time with this

**Comment by Lochnair** [comment]
I had a suspicion that could be the issue, glad you figured it out :)
